
/*
truncate table StatsData
*/

insert into StatsData(CategoryName, CountNum, Fields, Groups) values('HAU', 110, CONVERT(nvarchar(8), getutcdate(), 112)+ CONVERT(nvarchar(2), DATEPART(hour, GETUTCDATE())), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('HAU', 150, CONVERT(nvarchar(8), getutcdate(), 112)+ CONVERT(nvarchar(2), DATEPART(hour, GETUTCDATE())), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('HAU', 130, CONVERT(nvarchar(8), getutcdate(), 112)+ CONVERT(nvarchar(2), DATEPART(hour, GETUTCDATE())), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('HAU', 200, CONVERT(nvarchar(8), getutcdate(), 112)+ CONVERT(nvarchar(2), DATEPART(hour, GETUTCDATE())), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('HAU', 210, CONVERT(nvarchar(8), getutcdate(), 112)+ CONVERT(nvarchar(2), DATEPART(hour, GETUTCDATE())), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('HAU', 300, CONVERT(nvarchar(8), getutcdate(), 112)+ CONVERT(nvarchar(2), DATEPART(hour, GETUTCDATE())), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('HAU', 400, CONVERT(nvarchar(8), getutcdate(), 112)+ CONVERT(nvarchar(2), DATEPART(hour, GETUTCDATE())), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('HAU', 550, CONVERT(nvarchar(8), getutcdate(), 112)+ CONVERT(nvarchar(2), DATEPART(hour, GETUTCDATE())), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('HAU', 780, CONVERT(nvarchar(8), getutcdate(), 112)+ CONVERT(nvarchar(2), DATEPART(hour, GETUTCDATE())), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('HAU', 500, CONVERT(nvarchar(8), getutcdate(), 112)+ CONVERT(nvarchar(2), DATEPART(hour, GETUTCDATE())), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('HAU', 200, CONVERT(nvarchar(8), getutcdate(), 112)+ CONVERT(nvarchar(2), DATEPART(hour, GETUTCDATE())), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('HAU', 400, CONVERT(nvarchar(8), getutcdate(), 112)+ CONVERT(nvarchar(2), DATEPART(hour, GETUTCDATE())), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('HAU', 450, CONVERT(nvarchar(8), getutcdate(), 112)+ CONVERT(nvarchar(2), DATEPART(hour, GETUTCDATE())), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('HAU', 430, CONVERT(nvarchar(8), getutcdate(), 112)+ CONVERT(nvarchar(2), DATEPART(hour, GETUTCDATE())), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('HAU', 330, CONVERT(nvarchar(8), getutcdate(), 112)+ CONVERT(nvarchar(2), DATEPART(hour, GETUTCDATE())), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('HAU', 230, CONVERT(nvarchar(8), getutcdate(), 112)+ CONVERT(nvarchar(2), DATEPART(hour, GETUTCDATE())), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('HAU', 210, CONVERT(nvarchar(8), getutcdate(), 112)+ CONVERT(nvarchar(2), DATEPART(hour, GETUTCDATE())), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('HAU', 430, CONVERT(nvarchar(8), getutcdate(), 112)+ CONVERT(nvarchar(2), DATEPART(hour, GETUTCDATE())), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('HAU', 490, CONVERT(nvarchar(8), getutcdate(), 112)+ CONVERT(nvarchar(2), DATEPART(hour, GETUTCDATE())), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('HAU', 620, CONVERT(nvarchar(8), getutcdate(), 112)+ CONVERT(nvarchar(2), DATEPART(hour, GETUTCDATE())), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('HAU', 660, CONVERT(nvarchar(8), getutcdate(), 112)+ CONVERT(nvarchar(2), DATEPART(hour, GETUTCDATE())), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('HAU', 710, CONVERT(nvarchar(8), getutcdate(), 112)+ CONVERT(nvarchar(2), DATEPART(hour, GETUTCDATE())), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('HAU', 650, CONVERT(nvarchar(8), getutcdate(), 112)+ CONVERT(nvarchar(2), DATEPART(hour, GETUTCDATE())), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('HAU', 430, CONVERT(nvarchar(8), getutcdate(), 112)+ CONVERT(nvarchar(2), DATEPART(hour, GETUTCDATE())), '')

insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DAU', 1102, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DAU', 1590, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DAU', 2012, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DAU', 3453, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DAU', 2345, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DAU', 5645, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DAU', 3998, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DAU', 4320, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DAU', 3832, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DAU', 5032, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DAU', 4210, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DAU', 5432, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DAU', 6436, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DAU', 7543, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DAU', 8865, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DAU', 7768, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DAU', 9974, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DAU', 7112, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DAU', 7787, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DAU', 7324, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DAU', 8802, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DAU', 9943, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DAU', 10032, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DAU', 11202, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DAU', 9768, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DAU', 7789, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DAU', 8876, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DAU', 7644, CONVERT(nvarchar(8), getutcdate(), 112), '')

insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DARPU', 210, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DARPU', 232, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DARPU', 244, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DARPU', 265, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DARPU', 276, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DARPU', 299, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DARPU', 302, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DARPU', 283, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DARPU', 299, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DARPU', 321, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DARPU', 211, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DARPU', 299, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DARPU', 341, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DARPU', 331, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DARPU', 259, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DARPU', 292, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DARPU', 320, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DARPU', 329, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DARPU', 353, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DARPU', 398, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DARPU', 406, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DARPU', 429, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DARPU', 449, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DARPU', 476, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DARPU', 465, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DARPU', 430, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DARPU', 410, CONVERT(nvarchar(8), getutcdate(), 112), '')
insert into StatsData(CategoryName, CountNum, Fields, Groups) values('DARPU', 432, CONVERT(nvarchar(8), getutcdate(), 112), '')
