echo on
SQLCMD -S %1 -U %2 -P %3 -d %4 -i install-with-sample.sql

echo off
SQLCMD -S %1 -U %2 -P %3 -d %4 -i ./script/sspBatchDARPU.sql
SQLCMD -S %1 -U %2 -P %3 -d %4 -i ./script/sspBatchDAU.sql
SQLCMD -S %1 -U %2 -P %3 -d %4 -i ./script/sspBatchHAU.sql
SQLCMD -S %1 -U %2 -P %3 -d %4 -i ./script/uspAddMemberItemPurchase.sql
SQLCMD -S %1 -U %2 -P %3 -d %4 -i ./script/uspAddUseMemberItem.sql
SQLCMD -S %1 -U %2 -P %3 -d %4 -i ./script/uspComInsMemberItemPurchase.sql
SQLCMD -S %1 -U %2 -P %3 -d %4 -i ./script/uspComSelCoupon.sql
SQLCMD -S %1 -U %2 -P %3 -d %4 -i ./script/uspComSelCouponMember.sql
SQLCMD -S %1 -U %2 -P %3 -d %4 -i ./script/uspComSelGameEventMember.sql
SQLCMD -S %1 -U %2 -P %3 -d %4 -i ./script/uspComSelGameEvents.sql
SQLCMD -S %1 -U %2 -P %3 -d %4 -i ./script/uspComSelGiftDepository.sql
SQLCMD -S %1 -U %2 -P %3 -d %4 -i ./script/uspComSelItemList1.sql
SQLCMD -S %1 -U %2 -P %3 -d %4 -i ./script/uspComSelMember.sql
SQLCMD -S %1 -U %2 -P %3 -d %4 -i ./script/uspComSelMemberGameInfoes.sql
SQLCMD -S %1 -U %2 -P %3 -d %4 -i ./script/uspComSelMemberGameInfoStages.sql
SQLCMD -S %1 -U %2 -P %3 -d %4 -i ./script/uspComSelMemberItem.sql
SQLCMD -S %1 -U %2 -P %3 -d %4 -i ./script/uspComSelMemberItemPurchase.sql
SQLCMD -S %1 -U %2 -P %3 -d %4 -i ./script/uspComSelNotices.sql
SQLCMD -S %1 -U %2 -P %3 -d %4 -i ./script/uspComUdtGiftDepository.sql
SQLCMD -S %1 -U %2 -P %3 -d %4 -i ./script/uspComUdtItemList1.sql
SQLCMD -S %1 -U %2 -P %3 -d %4 -i ./script/uspComUdtMember.sql
SQLCMD -S %1 -U %2 -P %3 -d %4 -i ./script/uspComUdtMemberGameInfoes.sql
SQLCMD -S %1 -U %2 -P %3 -d %4 -i ./script/uspComUdtMemberGameInfoStages.sql
SQLCMD -S %1 -U %2 -P %3 -d %4 -i ./script/uspComUdtMemberItem.sql
SQLCMD -S %1 -U %2 -P %3 -d %4 -i ./script/uspComUdtMemberItemPurchase.sql
SQLCMD -S %1 -U %2 -P %3 -d %4 -i ./script/uspInsAnonymousRegMember.sql
SQLCMD -S %1 -U %2 -P %3 -d %4 -i ./script/uspInsRegMember.sql
SQLCMD -S %1 -U %2 -P %3 -d %4 -i ./script/uspSelAdminLogin.sql
SQLCMD -S %1 -U %2 -P %3 -d %4 -i ./script/uspSelAdminLogout.sql
REM SQLCMD -S %1 -U %2 -P %3 -d %4 -i ./script/uspSelCoupons.sql		:: uspSelCoupons is deplicated as business logic in CloudBread 2.0.1 release https://github.com/CloudBreadProject/CloudBread/issues/26
SQLCMD -S %1 -U %2 -P %3 -d %4 -i ./script/uspSelGameEvents.sql
SQLCMD -S %1 -U %2 -P %3 -d %4 -i ./script/uspSelGiftItemToMe.sql
SQLCMD -S %1 -U %2 -P %3 -d %4 -i ./script/uspSelItem1.sql
SQLCMD -S %1 -U %2 -P %3 -d %4 -i ./script/uspSelItemListAll.sql
SQLCMD -S %1 -U %2 -P %3 -d %4 -i ./script/uspSelLoginIDDupeCheck.sql
SQLCMD -S %1 -U %2 -P %3 -d %4 -i ./script/uspSelLoginInfo.sql
SQLCMD -S %1 -U %2 -P %3 -d %4 -i ./script/uspSelMemberGameInfoStages.sql
SQLCMD -S %1 -U %2 -P %3 -d %4 -i ./script/uspSelMemberItems.sql
SQLCMD -S %1 -U %2 -P %3 -d %4 -i ./script/uspSelNotices.sql
SQLCMD -S %1 -U %2 -P %3 -d %4 -i ./script/uspSelSendEmailToMember.sql
SQLCMD -S %1 -U %2 -P %3 -d %4 -i ./script/uspUdtConfirmedEmailAddress.sql
SQLCMD -S %1 -U %2 -P %3 -d %4 -i ./script/uspUdtCouponMember.sql
SQLCMD -S %1 -U %2 -P %3 -d %4 -i ./script/uspUdtGameEventMemberToItem.sql
SQLCMD -S %1 -U %2 -P %3 -d %4 -i ./script/uspUdtLoginInfo.sql
SQLCMD -S %1 -U %2 -P %3 -d %4 -i ./script/uspUdtMemberGameInfoStage.sql
SQLCMD -S %1 -U %2 -P %3 -d %4 -i ./script/uspUdtMoveGift.sql
SQLCMD -S %1 -U %2 -P %3 -d %4 -i ./script/uspUdtReturnItem.sql
SQLCMD -S %1 -U %2 -P %3 -d %4 -i ./script/uspUdtSellItem.sql
SQLCMD -S %1 -U %2 -P %3 -d %4 -i ./script/uspUdtSendGift.sql
